INSERT INTO uf (sigla, nome, codigo_ibge) 
VALUES ('ES', 'ESPIRITO SANTO', 32),
('MG', 'MINAS GERAIS', 31),
('RJ', 'RIO DE JANEIRO', 33),
('SP', 'SÃO PAULO', 35),
('RO', 'RONDÔNIA', 11),
('AC', 'ACRE', 12),
('AM', 'AMAZONAS', 13),
('RR', 'RORAIMA', 14),
('PA', 'PARÁ', 15),
('AP', 'AMAPÁ', 16),
('TO', 'TOCANTINS', 17),
('MA', 'MARANHÃO', 21),
('PI', 'PIAUI', 22),
('CE', 'CEARÁ', 23),
('RN', 'RIO GRANDE DO NORTE', 24),
('PB', 'PARAÍBA', 25),
('PE', 'PERNAMBUCO', 26),
('AL', 'ALAGOAS', 27),
('SE', 'SERGIPE', 28),
('BA', 'BAHIA', 29),
('PR', 'PARANÁ', 41),
('SC', 'SANTA CATARINA', 42),
('RS', 'RIO GRANDE DO SUL', 43),
('MS', 'MATO GROSSO DO SUL', 50),
('MT', 'MATO GROSSO', 51),
('GO', 'GOIÁS', 52),
('DF', 'DISTRITO FEDERAL', 53);
